### ISSUE TITLE
Trying to delete a User who is member of a project results in an error

### ISSUE THREAD

**Issue by MaPhiKo** [mosparo/mosparo#156] opened 2023-11-15 13:11 UTC
I tried to delete a testuser from my Mosparo installation.
Instead of deleting the user after confirming the choice, I was sent to an error page.

Since the user was deletable after removing them the project they were part of, I think the issue lies in the fact that they are referenced in the project_members table and not automatically removed from there before deleting them.

**Comment by zepich** [comment] 2023-11-15 18:26
Hi @MaPhiKo 

Thank you very much for reporting the issue.

I can confirm that it is not working, and as you write, because of the existing row in the second table.

We will add a fix for this in the next version.

Thank you very much!

Kind regards,

zepich

**Comment by zepich** [comment] 2023-11-19 18:42
Hi @MaPhiKo 

We've just released v1.0.5 which fixes the issue.

Thank you very much for your help!

**Closed by zepich** 2023-11-19 18:42 UTC
Labels: bug
