### ISSUE TITLE
IP lockout, Request delaying, Block equal submissions are not working

### ISSUE THREAD

**Issue by nik2025** [mosparo/mosparo#252] opened 2024-06-18 12:42 UTC
I try to make many requests with the same data from the same IP, but it does not effect. What can it be? 
![Bildschirmfoto 2024-06-18 um 14 42 03](https://github.com/mosparo/mosparo/assets/43677293/a5694337-4097-403f-990d-edb9fa35b738)

**Comment by zepich** [comment] 2024-06-18 13:06
Hi @nik2025 

Thank you very much for your question.

You want to test the feature "Block equal submissions", correct?

Do you submit the forms with equal data or just click the checkbox? The "Block equal submissions" feature counts only submitted forms.

Additionally, your IP address is not listed in the "IP allow list", correct?

Kind regards,

zepich

**Comment by nik2025** [comment] 2024-06-18 15:00
Thansk for the answer. All features like: IP lockout, Request delaying, Block equal submissions are not working. Yes, IP list is clear. In db are also no records in table. I try it with hidden captcha.

**Comment by zepich** [comment] 2024-06-18 15:39
Hi @nik2025 

Thank you very much for your answer.

Let's start with the "Block equal submissions" feature:
What IP address do you see when you look at the submissions list? You don't have to leak your IP address, but do you always see the same IP address for all your submissions?

Which setup do you use? Do you use the Docker image with a reverse proxy or did you install mosparo with the ZIP file manually?

Kind regards,

zepich

**Comment by nik2025** [comment] 2024-06-20 07:33
@zepich Hi, yes ip is the same in all submissions, i use DockerImage on amazon

**Comment by zepich** [comment] 2024-06-20 09:44
Hi @nik2025 

Thank you very much for your update.

I'm sorry for the trouble. Later today, I will set up a test environment and test it myself.

Kind regards,

zepich

**Comment by zepich** [comment] 2024-06-20 17:53
Hi @nik2025 

I've tested all three security features with a Docker image.

### Delay and Lockout features

I can confirm a bug in the delay and lockout features logic. These two features accidentally treat all IP addresses as if they would be on the allowed list. Because of this bug, the two security features are not working correctly right now. You can test that issue by adding any value to the allow list. You can enter anything, for example `999.999.999.999`. If you do that, the security features work correctly.

We'll release a new version with a fix for this issue over the weekend.

### Block equal submissions

Regarding the Block equal submissions, I've tested it with my default demo form, and everything worked correctly. But then I added a hidden field to the form, which was ignored by mosparo, and the feature stopped working and allowed all submissions. Have you also ignored fields in your form? You should see them when you look at the submission in mosparo. We'll also add a fix for this issue in the next version.

Thank you very much for your report and for helping make mosparo better!

Kind regards,

zepich

**Comment by zepich** [comment] 2024-06-23 18:53
Hi @nik2025 

### Delay and Lockout features

With version 1.2.3, the logic bug in the Delay and Lockout features is fixed, and the two features work again as expected.

### Block equal submissions

I've had another look at that issue, and the feature works correctly. To test the feature, I've added a hidden field to my demo form with a random value. In my earlier answer, I wrote that I could reproduce the issue with that feature, but I made a mistake.

I've sent the random value of the hidden field, which was ignored by mosparo, for verification to mosparo. This generates a different form data signature since mosparo did not validate the hidden field, and because of that, the submissions are not equal.

I guess you also have some random value in an ignored (hidden) field, which gets sent to mosparo for verification. Can you check if you send any random values to the mosparo API for verification?

Thank you very much for your help!

Kind regards,

zepich

**Comment by zepich** [comment] 2024-07-30 05:18
I close this issue. If you are still encouraging these problems, please post here or open a new one.

**Closed by zepich** 2024-07-30 05:18 UTC
Labels: bug
