### ISSUE TITLE
Support more platforms with docker images

### ISSUE THREAD

**Issue by mad73923** [mosparo/mosparo#244] opened 2024-06-13 12:14 UTC
Hi there

would it be possible to support more platforms as docker images?

Thanks & BR
Matthias

**Comment by zepich** [comment] 2024-06-13 12:20
Hi @mad73923

Thank you very much for your question.

Can you tell me more about what you mean by platforms? Do you mean other base images (instead of the official PHP one)? Or where do you want to use the image but can't because of this limitation?

Thank you very much for your help!

Kind regards,

zepich / Matthias :)

**Comment by mad73923** [comment] 2024-06-13 12:26
Hi @zepich 

thank you for your super fast reply!
You're right: feature-request is a little thin-worded.

What I'm asking for are image platforms for docker. eg:

- x86-64 (linux/amd64, linux/i386)
- ARM architectures (linux/arm/v5, linux/arm/v6, linux/arm/v7, linux/arm64)
- PowerPC and IBM Z (linux/ppc64le, linux/s390x)

Actually, I'm building an ARM64 image right now. If successful, I'll provide a PR.

BR
Matthias

**Comment by zepich** [comment] 2024-06-13 12:36
Hi @mad73923 

Thank you very much. Now I understand what you mean, and you're right: we should offer more platforms.

If you have a PR for arm64, that would be awesome. I will look into this topic. I think it should not be a big issue and probably (more or less) just an adjustment of the deployment process.

Thank you very much for bringing this issue to our attention!

Kind regards,

zepich

**Comment by mad73923** [comment] 2024-06-13 19:57
Hi @zepich 

I successfully got mosparo running in docker under linux/arm64.
The only thing I had to do was to run the docker build process with following command:
```
docker buildx build --platform linux/arm64 --build-arg="MOSPARO_VERSION=v1.2.1" -t mosparo/mosparo:latest .
```
I couldn't find any place where you build & deploy your docker images. Ever taught about github actions?

By the way: mosparo looks & feels awesome!! And works without hassle. It's been a while since I used such a nice piece of software which worked out of the box! :clap: 

BR
Matthias

P.S.: I got one more idea to improve: make the manual installation process (in docker) obsolete by using environment variables. Maybe a point for another enhancement issue?

**Comment by zepich** [comment] 2024-06-14 08:12
Hi @mad73923 

Thank you very much for your feedback, testing, and, in general, your help in making mosparo better!

> I successfully got mosparo running in docker under linux/arm64.
> The only thing I had to do was to run the docker build process with following command:

> docker buildx build --platform linux/arm64 --build-arg="MOSPARO_VERSION=v1.2.1" -t mosparo/mosparo:latest .

I found the same (or a similar) command yesterday and tested it to build it. I could not test it since I had no ARM CPU available for testing. But since we're using PHP, we should technically not have any problems with all platforms.

I will test it with an ARM CPU over the weekend. Additionally, I plan to release a new version on the weekend (or early next week) and try to add more platforms with that release (and for all future releases).

> I couldn't find any place where you build & deploy your docker images. Ever tought about github actions?

We build all our releases for mosparo itself and for all integrations, libraries, and other stuff like the website or the version/update files on a virtual server. For me, it was the easiest approach to set everything up and the most secure from our perspective because we do not have to store any credentials and certificates on a website.

Now, with the multiple platforms, we have a bigger issue because building takes time, and I would like to be able to have a fast release (right now, with one Docker platform (AMD64), it takes around 15 minutes to do all the stuff we have to do for a new version; testing the ARM64 build on a AMD64 platform tooks 20+ minutes alone). I looked yesterday at Docker Build Cloud, but the problem is that we would be limited in the number of builds we can make per month, or it can get expensive. GitHub Actions could be an alternative for that problem. But yeah, I didn't have time to look into GitHub Actions, and doing it with a simple shell script on a virtual server is way faster (at least when setting it up for the first Docker image)...

> By the way: mosparo looks & feels awesome!! And works without hassle. It's been a while since I used such a nice piece of software which worked out of the box! 👏

Thank you very much for your feedback and words! As a developer, this is the best thing to read and help continue working on such a project! Thank you very much!

> P.S.: I got one more idea to improve: make the manual installation process (in docker) obsolete by using environment variables. Maybe a point for another enhancement issue?

I once thought about this and that we could optimize the Docker image with it. However, I didn't have time to proceed with this adjustment. It would be great if you could create another issue for that improvement. Otherwise, I will have a look in the future anyway.

I wish you a nice day, and thank you for all your help!

Kind regards,

zepich

**Comment by zepich** [comment] 2024-06-16 15:27
Hi @mad73923 

We've just released version 1.2.2 with your pull request regarding the PostgreSQL extension. Additionally, as announced, the Docker image for this version (and all future versions) is available for multiple platforms (amd64, 386, arm64/v8, arm/v5, and arm/v7).

For these platforms, we're using Docker Build Cloud, which makes this task very easy and fast, so the whole deployment process will not take more time. For the other platforms that the PHP base image supports (mips64le, ppc64le, and s390x), we do not have a solution right now since the Docker Build Cloud does not support them (as far as I understand).

What's your opinion about these platforms? Do you think these platforms are required? I also have the problem of not having a server on such a platform, which makes it impossible to test the images. Do you know a hoster with such a platform?

Thank you very much for your help!

Kind regards,

zepich

**Comment by mad73923** [comment] 2024-06-16 15:38
Hi @zepich 

you're to fast for my little time I can spend here :see_no_evil: 
Here's what I was writing before your answer:

thank you for your detailed answer!
Regarding github actions:
The free plan will include 2000 minutes of building your images ([Source](https://docs.github.com/de/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes))
If this doesn't sound good enough to you I highly recommend running a [self hosted github action runner](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) on your VM. I do the same for some gitlab projects. No more manually starting any build scripts!
I'll provide a first draft for the action manifest. The only thing missing is you to [add your Dockerhub credentials in your repo](https://docs.github.com/de/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository).

---

Here's what I have to say after your 2nd answer:
Thanks for the update! I didn't know Docker Build Cloud so far.

> For the other platforms that the PHP base image supports (mips64le, ppc64le, and s390x), we do not have a solution right now since the Docker Build Cloud does not support them (as far as I understand). What's your opinion about these platforms? Do you think these platforms are required? I also have the problem of not having a server on such a platform, which makes it impossible to test the images. Do you know a hoster with such a platform?

These are some very special platforms which I just copied from the docker docs. As long as noone requests them it's not worth the effort to provide them. with the setup you just delivered with 1.2.2 you will cover 99% of the usecases I guess.

Regarding the hoster: I use Hetzner for arm64.

PR for github actions will be here in a sec.

BR
Matthias

**Comment by zepich** [comment] 2024-06-19 17:09
Hi @mad73923 

> you're to fast for my little time I can spend here 🙈
Here's what I was writing before your answer:

My biggest issue in the past two years: Time... :D Don't worry, I can understand that! You answered on Sunday, but I didn't have time to answer you until now... So, I'm not always that fast... :)

Thank you very much for your answer and explanation regarding GitHub Action Runner. I didn't know that it's even possible to host it on our server. I will look into that one.

Also, thank you for your pull request with the actions configuration. Since we're using Docker Build Cloud now, using GitHub Actions to build the images would be a good option. Before, with only one image, I tested the image before I pushed it. That's not possible anymore, so we have to push it anyway, and therefore, it doesn't matter if we build it locally with Docker Build Cloud or with GitHub Actions.

> These are some very special platforms which I just copied from the docker docs. As long as noone requests them it's not worth the effort to provide them. with the setup you just delivered with 1.2.2 you will cover 99% of the usecases I guess.

Perfect! I have the same opinion. In the end, the Dockerfile (and mosparo itself) is open source, so if someone needs an image for one of these platforms, they can build it pretty easily (as you were able to make the ARM image without any troubles). And if, at one point, somebody will over virtual servers on these platforms, we're open to discussing it again.

Thank you regarding Hetzer. I've tested the ARM image with a Hetzner ARM VM and a Raspberry Pi, which both worked perfectly... :)

I will close this issue since it's solved.

Thank you very much, and have a great day!

Kind regards,

zepich

**Closed by zepich** 2024-06-19 17:09 UTC
Labels: enhancement
